### ISSUE TITLE
Job as a value object?

### ISSUE THREAD

**Issue by EmanueleMinotto** [taueres/easy-crontab#1]
`EasyCrontab\Job` attributes could be random and illegal (day of the week 10 or month 14, for example) and create [undefined behaviours](http://stackoverflow.com/a/26766693).
What about switching from an entity to a value object? I can submit a PR if you want.

**Comment by taueres** [comment]
@EmanueleMinotto Thank you for your suggestion!
I think this is a good idea. Even though no attributes validation is implemented so far in the project.
I've only got a doubt about value objects: they do not allow easy editing of existing jobs (see the edit example I wrote in the Readme). With the current API, users need to remove the old job and then add again the modified version.

What do you think?

**Comment by EmanueleMinotto** [comment]
uhm... probably something like this could be a solution:

``` php
public function withAnotherDayOfTheWeek($dayOfWeek) {
    $clone = clone $this;
    $clone->dayOfWeek = $dayOfWeek;

    return new self((string) $clone);
}
```

The private attribute of `$clone` can be changed thanks to the [particular PHP visibility](http://www.php.net/manual/en/language.oop5.visibility.php#language.oop5.visibility-other-objects).

The status of `$this` isn't changed and validation is still included, anyway every setter should be removed in this case, because too much ambiguous.
